rootProject.name = "Binom"

include(":env")
include(":pool")
include(":cleaner")
include(":crc")
include(":io")
include(":scram")
include(":properties-serialization")
include(":charset")
include(":core")
include(":network-common")
include(":concurrency")
 include(":benchmark")
// include(":uuid")
include(":pipe")
include(":jwt")
include(":testing")
include(":memory")
// include(":uuid-serialization")
include(":date")
include(":console")
//include(":url")
include(":strong")
include(":strong:strong-properties")
include(":strong:strong-web-server")
// include(":strong:strong-application")
include(":file")
include(":db")
include(":thread")
include(":binom-coroutines")
// include(":atomic")
include(":file-watch")
include(":db:kmigrator")
// include(":db:firebird")
include(":db:db-serialization-annotations")
include(":db:db-serialization")
// include(":db:db-serialization:benchmark")
include(":db:indexed-db")
include(":db:redis")
include(":rpc")
include(":metric")
include(":metric:prometheus")
include(":network")
include(":db:sqlite")
include(":db:postgresql-async")
include(":db:tarantool-client")
include(":http")
include(":http:http-rest")
include(":dns")
include(":mq")
include(":mq:nats")
include(":httpClient")
include(":httpClient:http-client-rest")
include(":httpServer")
include(":httpServer:http-server-rest")
include(":compression")
include(":collections")
include(":xml")
include(":xml:xsd")
include(":xml:xml-serialization")
include(":logger")
include(":webdav")
include(":ssl")
include(":s3")
include(":process")
include(":flux")
include(":smtp")
include(":signal")
include(":socket")
// include(":nio")
include(":coroutines")
// include(":http-route")
// include(":http-route:http-kotlin-plugin")
// include(":http-route:http-kotlin-plugin-gradle")
// include(":route-plugin:route-plugin")
// include(":route-plugin:route-plugin-gradle")
// include(":route-plugin:route-plugin-native")

// include(":lite-network")

// include(":examples:view")

// include(":examples:echoServer")
// include(":examples:simpleHttpServer")
// include(":examples:nioHttpServer")
// include(":examples:nioEchoReversServer")
// include(":examples:clienthttp")
// include(":examples:zlib")
// include(":examples:wsChat")
// include(":examples:wsEchoDeley")
// include(":examples:strong-example")
// include(":examples:read-write-file")
