rootProject.name = "Binom"

include(":env")
include(":pool")
include(":cleaner")
include(":crc")
include(":io")
include(":scram")
include(":charset")
include(":core")
include(":concurrency")
include(":uuid")
include(":pipe")
include(":uuid-serialization")
include(":date")
include(":console")
include(":url")
include(":strong")
include(":strong:strong-application")
include(":file")
include(":db")
include(":thread")
include(":binom-coroutines")
include(":atomic")
include(":db:kmigrator")
include(":db:db-serialization-annotations")
include(":db:db-serialization")
include(":db:redis")
include(":rpc")
include(":metric")
include(":metric:prometheus")
include(":network")
include(":db:sqlite")
include(":db:postgresql-async")
include(":db:tarantool-client")
include(":http")
include(":dns")
include(":mq:nats")
include(":httpClient")
include(":httpServer")
include(":compression")
include(":collections")
include(":xml")
include(":xml:xsd")
include(":xml:xml-serialization")
include(":logger")
include(":webdav")
include(":ssl")
include(":s3")
include(":process")
include(":flux")
include(":smtp")
include(":signal")
include(":socket")
// include(":nio")
include(":coroutines")

// include(":examples:view")

// include(":examples:echoServer")
// include(":examples:simpleHttpServer")
// include(":examples:nioHttpServer")
// include(":examples:nioEchoReversServer")
// include(":examples:clienthttp")
// include(":examples:zlib")
// include(":examples:wsChat")
// include(":examples:wsEchoDeley")
// include(":examples:strong-example")
// include(":examples:read-write-file")
