[versions]
kotlin = "2.1.20"
binom-io = "1.0.0-SNAPSHOT"
binom-url = "0.0.9"
binom-uuid = "0.0.7"
binom-atomic = "1.0.0-SNAPSHOT"
binom-bitarray = "0.2.7"
kotlinx-serialization = "1.8.1"
kotlinx-coroutines = "1.10.2"
android = "8.9.1"
bouncycastle = "1.68"
ionspin-bignum = "0.3.9"

[libraries]
bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle"}
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle"}
ionspin-bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "ionspin-bignum"}
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
binom-url = { module = "pw.binom:url", version.ref = "binom-url" }
binom-uuid = { module = "pw.binom:uuid", version.ref = "binom-uuid" }
binom-atomic = { module = "pw.binom:atomic", version.ref = "binom-atomic" }
binom-bitarray = { module = "pw.binom:bitarray", version.ref = "binom-bitarray"}
kaml = { module = "com.charleskorn.kaml:kaml", version = "0.67.0"}

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
