package pw.binom.scram

class ScramClient {
    companion object {
        /**
         * Length (in characters, bytes) of the nonce generated by default (if no nonce supplier is provided)
         */
        const val DEFAULT_NONCE_LENGTH = 24
    }
}
