package pw.binom.bluetooth

import kotlin.jvm.JvmInline

@JvmInline
value class AttributeId(val raw: Short) {
  companion object {
    val SDP_ATTR_RECORD_HANDLE = AttributeId(0x0000)
    val SDP_ATTR_SVCLASS_ID_LIST = AttributeId(0x0001)
    val SDP_ATTR_RECORD_STATE = AttributeId(0x0002)
    val SDP_ATTR_SERVICE_ID = AttributeId(0x0003)
    val SDP_ATTR_PROTO_DESC_LIST = AttributeId(0x0004)
    val SDP_ATTR_BROWSE_GRP_LIST = AttributeId(0x0005)
    val SDP_ATTR_LANG_BASE_ATTR_ID_LIST = AttributeId(0x0006)
    val SDP_ATTR_SVCINFO_TTL = AttributeId(0x0007)
    val SDP_ATTR_SERVICE_AVAILABILITY = AttributeId(0x0008)
    val SDP_ATTR_PFILE_DESC_LIST = AttributeId(0x0009)
    val SDP_ATTR_DOC_URL = AttributeId(0x000a)
    val SDP_ATTR_CLNT_EXEC_URL = AttributeId(0x000b)
    val SDP_ATTR_ICON_URL = AttributeId(0x000c)
    val SDP_ATTR_ADD_PROTO_DESC_LIST = AttributeId(0x000d)
    val SDP_ATTR_GROUP_ID = AttributeId(0x0200)
    val SDP_ATTR_IP_SUBNET = AttributeId(0x0200)
    val SDP_ATTR_VERSION_NUM_LIST = AttributeId(0x0200)
    val SDP_ATTR_SUPPORTED_FEATURES_LIST = AttributeId(0x0200)
    val SDP_ATTR_GOEP_L2CAP_PSM = AttributeId(0x0200)
    val SDP_ATTR_SVCDB_STATE = AttributeId(0x0201)
    val SDP_ATTR_MPSD_SCENARIOS = AttributeId(0x0200)
    val SDP_ATTR_MPMD_SCENARIOS = AttributeId(0x0201)
    val SDP_ATTR_MPS_DEPENDENCIES = AttributeId(0x0202)
    val SDP_ATTR_SERVICE_VERSION = AttributeId(0x0300)
    val SDP_ATTR_EXTERNAL_NETWORK = AttributeId(0x0301)
    val SDP_ATTR_SUPPORTED_DATA_STORES_LIST = AttributeId(0x0301)
    val SDP_ATTR_DATA_EXCHANGE_SPEC = AttributeId(0x0301)
    val SDP_ATTR_NETWORK = AttributeId(0x0301)
    val SDP_ATTR_FAX_CLASS1_SUPPORT = AttributeId(0x0302)
    val SDP_ATTR_REMOTE_AUDIO_VOLUME_CONTROL = AttributeId(0x0302)
    val SDP_ATTR_MCAP_SUPPORTED_PROCEDURES = AttributeId(0x0302)
    val SDP_ATTR_FAX_CLASS20_SUPPORT = AttributeId(0x0303)
    val SDP_ATTR_SUPPORTED_FORMATS_LIST = AttributeId(0x0303)
    val SDP_ATTR_FAX_CLASS2_SUPPORT = AttributeId(0x0304)
    val SDP_ATTR_AUDIO_FEEDBACK_SUPPORT = AttributeId(0x0305)
    val SDP_ATTR_NETWORK_ADDRESS = AttributeId(0x0306)
    val SDP_ATTR_WAP_GATEWAY = AttributeId(0x0307)
    val SDP_ATTR_HOMEPAGE_URL = AttributeId(0x0308)
    val SDP_ATTR_WAP_STACK_TYPE = AttributeId(0x0309)
    val SDP_ATTR_SECURITY_DESC = AttributeId(0x030a)
    val SDP_ATTR_NET_ACCESS_TYPE = AttributeId(0x030b)
    val SDP_ATTR_MAX_NET_ACCESSRATE = AttributeId(0x030c)
    val SDP_ATTR_IP4_SUBNET = AttributeId(0x030d)
    val SDP_ATTR_IP6_SUBNET = AttributeId(0x030e)
    val SDP_ATTR_SUPPORTED_CAPABILITIES = AttributeId(0x0310)
    val SDP_ATTR_SUPPORTED_FEATURES = AttributeId(0x0311)
    val SDP_ATTR_SUPPORTED_FUNCTIONS = AttributeId(0x0312)
    val SDP_ATTR_TOTAL_IMAGING_DATA_CAPACITY = AttributeId(0x0313)
    val SDP_ATTR_SUPPORTED_REPOSITORIES = AttributeId(0x0314)
    val SDP_ATTR_MAS_INSTANCE_ID = AttributeId(0x0315)
    val SDP_ATTR_SUPPORTED_MESSAGE_TYPES = AttributeId(0x0316)
    val SDP_ATTR_PBAP_SUPPORTED_FEATURES = AttributeId(0x0317)
    val SDP_ATTR_MAP_SUPPORTED_FEATURES = AttributeId(0x0317)
    val SDP_ATTR_SPECIFICATION_ID = AttributeId(0x0200)
    val SDP_ATTR_VENDOR_ID = AttributeId(0x0201)
    val SDP_ATTR_PRODUCT_ID = AttributeId(0x0202)
    val SDP_ATTR_VERSION = AttributeId(0x0203)
    val SDP_ATTR_PRIMARY_RECORD = AttributeId(0x0204)
    val SDP_ATTR_VENDOR_ID_SOURCE = AttributeId(0x0205)
    val SDP_ATTR_HID_DEVICE_RELEASE_NUMBER = AttributeId(0x0200)
    val SDP_ATTR_HID_PARSER_VERSION = AttributeId(0x0201)
    val SDP_ATTR_HID_DEVICE_SUBCLASS = AttributeId(0x0202)
    val SDP_ATTR_HID_COUNTRY_CODE = AttributeId(0x0203)
    val SDP_ATTR_HID_VIRTUAL_CABLE = AttributeId(0x0204)
    val SDP_ATTR_HID_RECONNECT_INITIATE = AttributeId(0x0205)
    val SDP_ATTR_HID_DESCRIPTOR_LIST = AttributeId(0x0206)
    val SDP_ATTR_HID_LANG_ID_BASE_LIST = AttributeId(0x0207)
    val SDP_ATTR_HID_SDP_DISABLE = AttributeId(0x0208)
    val SDP_ATTR_HID_BATTERY_POWER = AttributeId(0x0209)
    val SDP_ATTR_HID_REMOTE_WAKEUP = AttributeId(0x020a)
    val SDP_ATTR_HID_PROFILE_VERSION = AttributeId(0x020b)
    val SDP_ATTR_HID_SUPERVISION_TIMEOUT = AttributeId(0x020c)
    val SDP_ATTR_HID_NORMALLY_CONNECTABLE = AttributeId(0x020d)
    val SDP_ATTR_HID_BOOT_DEVICE = AttributeId(0x020e)
    val SDP_PRIMARY_LANG_BASE: Short = 0x0100
    val SDP_ATTR_SVCNAME_PRIMARY = AttributeId((0x0000 + SDP_PRIMARY_LANG_BASE).toShort())
    val SDP_ATTR_SVCDESC_PRIMARY = AttributeId((0x0001 + SDP_PRIMARY_LANG_BASE).toShort())
    val SDP_ATTR_PROVNAME_PRIMARY = AttributeId((0x0002 + SDP_PRIMARY_LANG_BASE).toShort())
  }
}
