package pw.binom.db.serialization

interface EntityDescription2 {
  interface Field {
    val name: String
    val useQuotes: Boolean
    val autoGenerated: Boolean
    val index: Boolean
    val id: Boolean
  }

  val fields: Map<String, Field>

  val idFields
    get() = fields.values.filter { it.id }
}
