package pw.binom.db.serialization

import kotlinx.serialization.SerialInfo

/**
 * Define autogenerated column. This column will lost on insert operations.
 */
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.BINARY)
@SerialInfo
annotation class AutoGenerated