package pw.binom.db.serialization

import kotlinx.serialization.MetaSerializable

/**
 * Define autogenerated column. This column will lose on insert operations.
 */
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.BINARY)
@MetaSerializable
annotation class AutoGenerated
