package pw.binom

enum class Platform {
    MINGW_X86,
    MINGW_X64,
    MINGW_ARM_32,
    MINGW_ARM_64,
    LINUX_ARM_32,
    LINUX_ARM_64,
    LINUX_MIPS_32,
    LINUX_MIPSEL_32,
    LINUX_64,
    LINUX_X86,
    MACOS_X86,
    MACOS_X64,
    MACOS_ARM_32,
    MACOS_ARM_X64,
    IOS_ARM_X86,
    IOS_ARM_64,
    IOS_ARM_32,
    IOS_X86,
    IOS_X64,
    TVOS_X86,
    TVOS_ARM_64,
    TVOS_ARM_32,
    WATCHOS_X86,
    WATCHOS_ARM_64,
    WATCHOS_ARM_32,
    JVM,
    JS,
    WASM,
    UNKNOWN,
    ANDROID_ARM_X32,
    ANDROID_ARM_X64,
    ANDROID_X86,
    ANDROID_X64,
}
