package pw.binom

object Versions {
    val LIB_VERSION = "0.1.32-RC"
    val TEST_CONTAINERS_VERSION = "0.1.2"
    val KOTLIN_VERSION = BuildConfig.KOTLIN_VERSION
    val IONSPIN_BIGNUM_VERSION = BuildConfig.IONSPIN_BIGNUM_VERSION
    val KOTLINX_SERIALIZATION_VERSION = BuildConfig.KOTLINX_SERIALIZATION_VERSION

    //    val KOTLINX_COROUTINES_VERSION = "1.5.1-new-mm-dev2"
    val KOTLINX_COROUTINES_VERSION = BuildConfig.KOTLINX_COROUTINES_VERSION
//    val KOTLINX_COROUTINES_VERSION = "1.5.2"
}
